### ISSUE TITLE
Can't get window.location

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1150]
Assuming a function to get the window as a Result, like this:

```
fn get_window () -> Result<web_sys::Window, JsValue> {
    web_sys::window().ok_or(JsValue::from_str("couldn't get window"))
}
```

I can successfully get some other properties of the window, like inner_width:

```
fn get_inner_width() -> Result<f64, JsValue> {
    let size = get_window()?.inner_width()?.as_f64().ok_or(JsValue::from_str("uhoh"))?;
    Ok(size)
}
```

But trying to get the `location` fails:

```
let location_origin = get_window()?.location().origin()?; 
```

In case it matters, the use case is something like this:
```
pub fn same_origin(url:&str) -> Result<bool, JsValue> {
    if url.starts_with("http://") || url.starts_with("https://") {
        let location_origin = get_window()?.location().origin()?; 
        let url = Url::new(url)?;
        Ok(url.origin() == location_origin)
    } else {
        Ok(true)
    }
}
```

Not sure if this is related to #780 or #659

**Comment by chinedufn** [comment]
Try this https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Document.html#method.location 

(Sorry on mobile typing is a pain)

**Comment by dakom** [comment]
Nope, same bug

**Comment by alexcrichton** [comment]
I think this may have been a bug I've forgotten to publish actually, I just published new versions of all crates though! @dakom want to update and see if it's fixed now?

**Comment by dakom** [comment]
cargo-update didn't fix it for me... maybe I'm doing something wrong?

Here's the offending line: https://github.com/dakom/pure3d/blob/a630d4bddaf850d543d7d73bbd814405295468b0/crates/web_sys_loaders/src/xhr.rs#L72

**Comment by alexcrichton** [comment]
Ah I can't get that to build unfortunately, do you have some steps though that could help me out?

**Comment by dakom** [comment]
The project as a whole is an early work-in-progress, but commenting out that block gets it to compile at least:

```rust
pub fn same_origin(url:&str) -> Result<bool, JsValue> {
    /*
    if url.starts_with("http://") || url.starts_with("https://") {
        let location_origin = get_window()?.location().origin()?; 
        let url = Url::new(url)?;
        Ok(url.origin() == location_origin)
    } else {
        Ok(true)
    }
    */
    Ok(true)
}
```

**Comment by alexcrichton** [comment]
Oh if it's just a question of compiling (sorry, I thought it was runtime failing), then [as mentioned in the documentation](https://docs.rs/web-sys/0.3.7/web_sys/struct.Window.html#method.location) you'll need to enable a few features of the `web-sys` crate

**Comment by dakom** [comment]
Ahhh... added `Window` but missed `Location`. Thanks again!

(btw what's the policy of closing comments? Should I close it myself in a case like this or wait for you / one of the maintainers to close it at their discretion?)

**Comment by alexcrichton** [comment]
Either way's fine, I can do so here!
