### ISSUE TITLE
future incompat dependencies

### ISSUE THREAD

**Issue by Nanai10a** [rustwasm/wasm-bindgen#3356]
I did `cargo install wasm-bindgen-cli`, and seen:

```
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, multipart v0.18.0, wasmparser v0.59.0, wasmparser v0.77.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

with using:

```
rustup 1.25.2 (2023-02-04)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0-nightly (171693274 2023-03-14)`
```

here is a dependency tree:

- wasm-bindgen-cli v0.2.84
  - rouille v3.6.1
    - **multipart v0.18.0**
      - **buf_redux v0.8.4**
  - walrus v0.19.0
    - **wasmparser v0.77.0**
  - wasm-bindgen-cli-support v0.2.84
    - wit-validator v0.2.1
      - **wasmparser v0.59.0**

and report:

```
To solve this problem, you can try the following approaches:


- Some affected dependencies have newer versions available.
You may want to consider updating them to a newer version to see if the issue has been fixed.

wasmparser v0.59.0 has the following newer versions available: 0.60.0, 0.60.1, 0.60.2, 0.61.0, 0.62.0, 0.63.0, 0.63.1, 0.64.0, 0.65.0, 0.66.0, 0.67.0, 0.68.0, 0.69.0, 0.69.1, 0.69.2, 0.70.0, 0.71.0, 0.72.0, 0.73.0, 0.73.1, 0.74.0, 0.75.0, 0.76.0, 0.77.0, 0.78.0, 0.78.1, 0.78.2, 0.79.0, 0.80.0, 0.80.1, 0.80.2, 0.81.0, 0.82.0, 0.83.0, 0.84.0, 0.85.0, 0.86.0, 0.87.0, 0.88.0, 0.89.0, 0.89.1, 0.90.0, 0.91.0, 0.92.0, 0.93.0, 0.94.0, 0.95.0, 0.96.0, 0.97.0, 0.98.1, 0.99.0, 0.100.0, 0.101.0, 0.101.1, 0.102.0
wasmparser v0.77.0 has the following newer versions available: 0.78.0, 0.78.1, 0.78.2, 0.79.0, 0.80.0, 0.80.1, 0.80.2, 0.81.0, 0.82.0, 0.83.0, 0.84.0, 0.85.0, 0.86.0, 0.87.0, 0.88.0, 0.89.0, 0.89.1, 0.90.0, 0.91.0, 0.92.0, 0.93.0, 0.94.0, 0.95.0, 0.96.0, 0.97.0, 0.98.1, 0.99.0, 0.100.0, 0.101.0, 0.101.1, 0.102.0


- If the issue is not solved by updating the dependencies, a fix has to be
implemented by those dependencies. You can help with that by notifying the
maintainers of this problem (e.g. by creating a bug report) or by proposing a
fix to the maintainers (e.g. by creating a pull request):

  - buf_redux@0.8.4
  - Repository: https://github.com/abonander/buf_redux
  - Detailed warning command: `cargo report future-incompatibilities --id 1 --package buf_redux@0.8.4`

  - multipart@0.18.0
  - Repository: http://github.com/abonander/multipart
  - Detailed warning command: `cargo report future-incompatibilities --id 1 --package multipart@0.18.0`

  - wasmparser@0.59.0
  - Repository: https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasmparser
  - Detailed warning command: `cargo report future-incompatibilities --id 1 --package wasmparser@0.59.0`

  - wasmparser@0.77.0
  - Repository: https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasmparser
  - Detailed warning command: `cargo report future-incompatibilities --id 1 --package wasmparser@0.77.0`

- If waiting for an upstream fix is not an option, you can use the `[patch]`
section in `Cargo.toml` to use your own version of the dependency. For more
information, see:
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section
```

Thanks.

**Comment by daxpedda** [comment]
It's strange that this gives a warning, `wit-validator` is a dev-dependency.
This might be because we aren't using `resolver = "2"`.

**Comment by alexcrichton** [comment]
As concluded on https://github.com/rustwasm/wasm-bindgen/pull/3358, not fixed by that PR.

**Comment by alexcrichton** [comment]
I've fixed `wasmparser` with a 0.77.1 version to avoid the need to update walrus for now. Not sure how best to tackle `rouille` though

**Comment by szilardszaloki** [comment]
Hi there,
Are there any recent updates on this one?
Still getting:
```
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, multipart v0.18.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```
Thanks!

**Comment by seanwatters** [comment]
> I've fixed `wasmparser` with a 0.77.1 version to avoid the need to update walrus for now. Not sure how best to tackle `rouille` though

@alexcrichton 

would it be worth the effort if i took the time to switch all the `rouille` code to `axum`? i'd be happy to do the work and open a PR but don't want to spend time on that if it's not the right direction to take this.

seems like `rouille` is only used in the `crates/cli/src/wasm_bindgen_test_runner/headless.rs` and `crates/cli/src/wasm_bindgen_test_runner/server.rs` files. the `headless.rs` file probably just needs to switch the the `url` crate (and any adjustments for difference in API), and the `server.rs` file is where the switch to `axum` would come in.
