### ISSUE TITLE
Generated bindings with no-modules target causes error in web extensions

### ISSUE THREAD

**Issue by holly-hacker** [rustwasm/wasm-bindgen#3398]
### Describe the Bug

I am trying to build a web extension using [Mubelotix/wasm-extension-template](https://github.com/Mubelotix/wasm-extension-template) as a template, but I get a javascript error inside the generated bindings when loading the generated extension in a browser:
![Uncaught TypeError: Cannot read properties of null (reading 'src')](https://user-images.githubusercontent.com/13605369/233978151-982ecd17-e17e-432e-a777-17bab3fbf9e0.png)

The linked template uses wasm-pack with the cli argument `--target=no-modules` which generates binding code that starts like so:
```js
let wasm_bindgen;
(function() {
    const __exports = {};
    let script_src;
    if (typeof document === 'undefined') {
        script_src = location.href;
    } else {
        script_src = new URL(document.currentScript.src, location.href).toString();
    }
    let wasm;
    // ...
```

In the context of a web extension, `document` is defined but `document.currentScript` is null. This causes a TypeError when `document.currentScript.src` is executed.

The current `main` branch (commit 153a6aa9c7a989c1865df7f93b2ddbca1113a175) seems to output different code, as seen [here](https://github.com/rustwasm/wasm-bindgen/blob/153a6aa9c7a989c1865df7f93b2ddbca1113a175/crates/cli-support/src/js/mod.rs#L385):
```js
if (typeof document !== 'undefined') {
    script_src = new URL(document.currentScript.src, location.href).toString();
}
```

I haven't managed to build the `main` branch of wasm-pack yet to try this out, but I assume it will produce the same error.

### Steps to Reproduce

1. Clone [Mubelotix/wasm-extension-template](https://github.com/Mubelotix/wasm-extension-template)
2. Build the extension with `sh build.sh`
3. Inside a chromium-based browser, load the extension as an unpacked extension by following [Chrome's documentation](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked).
4. Browse to https://example.com, open devtools and observe the error.

### Expected Behavior

Wasm-bindgen should account for cases where `document.currentScript` is `null` or `undefined` and have a fallback.

### Actual Behavior

Wasm-bindgen assumes `document.currentScript` is not null when `document` is not undefined.

### Additional Context

- wasm-pack version: 0.11.0
- wasm-bindgen version: 0.2.83 (shipped with wasm-pack, I presume)

I am testing on Windows using the Brave browser.

**Comment by rimutaka** [comment]
The same issue came up in Chrome and Firefox on Ubuntu. _wasm-pack v0.11.0_ and _wasm-bindgen v0.2.84_.

**Comment by holly-hacker** [comment]
I only started using web extensions yesterday, so my apologies if I get something wrong here.

The web extension in the linked template creates a [content script](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) (injected with a [static declaration](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#static-declarative)), meaning the script gets just loaded into the content page without any extra context info. It seems they can access a [subset of the webextension api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis) which includes [`runtime.getURL`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getURL), which can be used to get a link to the absolute extension url when given a relative url (you'd do this for the .js file):
```js
let fullURL = browser.runtime.getURL("beasts/frog.html");
console.log(fullURL);
// Returns something like:
// moz-extension://2c127fa4-62c7-7e4f-90e5-472b45eecfdc/beasts/frog.html
```
I'm not quite sure how to get the relative url to the current script file though. You could read the the manifest using [`runtime.getManifest`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getManifest) but that can include multiple content scripts for the current page.

**Comment by daxpedda** [comment]
So I guess it's not possible.
As I was saying in https://github.com/rustwasm/wasm-bindgen/pull/3402#discussion_r1176190444, `script_src` should probably stay `undefined` then.

**Comment by daxpedda** [comment]
Fixed by https://github.com/rustwasm/wasm-bindgen/pull/3402.

**Comment by lukaslueg** [comment]
The error is still present when using `0.2.85`:

```raw
caught TypeError: Cannot read properties of null (reading 'src')
    at macro_railroad_ext.js:6:53
    at macro_railroad_ext.js:432:3
```

which refers to

```javascript
script_src = new URL(document.currentScript.src, location.href).toString();
```

It seems to me #3402 is wrong:

```javascript
typeof document.currentScript !== 'null'
```

I'm not a JS-guy, but afaics this can never be `false`: `typeof document.currentScript` [is defined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) to be `object` if `document.currentScript` is `null`, so the check can't actually work.

**Comment by daxpedda** [comment]
Indeed, we should just not use `typeof` here.

**Comment by daxpedda** [comment]
@lukaslueg could you check with #3426?

**Comment by lukaslueg** [comment]
@daxpedda, help me out here: The offending js-glue is ultimately provided by the `wasm-pack`-binary or by the `wasm-bindgen` lib-dependency?

**Comment by daxpedda** [comment]
It's the `wasm-bindgen-cli` binary.
So `cargo install wasm-bindgen-cli --git https://github.com/daxpedda/wasm-bindgen --branch fix-3402` (you might need `--force`) should probably do it.

If there is an error about non-matching versions, use the following in your `Cargo.toml`:
```toml
[patch.crates-io]
js-sys = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "fix-3402" }
wasm-bindgen = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "fix-3402" }
wasm-bindgen-futures = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "fix-3402" }
wasm-bindgen-test = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "fix-3402" }
web-sys = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "fix-3402" }
```

**Comment by lukaslueg** [comment]
The `fix-3402`-branch of the `wasm-bindgen-cli` package fixes the problem

**Comment by daxpedda** [comment]
Thank you for the quick back-and-forth!

**Comment by lukaslueg** [comment]
@daxpedda Thanks for the fix. Will there be a point release?

**Comment by daxpedda** [comment]
Probably not, though this isn't my purview.

**Comment by lukaslueg** [comment]
h/t @alexcrichton to reflect on this: This (fixed) bug is currently preventing WebExtensions from building working releases

**Comment by alexcrichton** [comment]
Ok, I've opened https://github.com/rustwasm/wasm-bindgen/pull/3429 for a bump
