### ISSUE TITLE
Returning `Vec<String>` from an async function fails to compile

### ISSUE THREAD

**Issue by FredrikNoren** [rustwasm/wasm-bindgen#3793]
### Describe the Bug

This code:
```rust
#[wasm_bindgen]
pub async fn get_strings() -> Vec<String> {
    vec!["hello".to_string(), "world".to_string()]
}
```

### Expected Behavior

Should compile,

### Actual Behavior

But gives the following compilation error:
```
the trait bound `wasm_bindgen::JsValue: From<Vec<std::string::String>>` is not satisfied
the following other types implement trait `From<T>`:
  <wasm_bindgen::JsValue as From<bool>>
  <wasm_bindgen::JsValue as From<isize>>
  <wasm_bindgen::JsValue as From<i8>>
  <wasm_bindgen::JsValue as From<i16>>
  <wasm_bindgen::JsValue as From<i32>>
  <wasm_bindgen::JsValue as From<i64>>
  <wasm_bindgen::JsValue as From<i128>>
  <wasm_bindgen::JsValue as From<usize>>
and 100 others
required for `Vec<std::string::String>` to implement `Into<wasm_bindgen::JsValue>`
required for `Vec<std::string::String>` to implement `IntoJsResult`
```

### Additional Context

`wasm-bindgen = "0.2"`

**Comment by matthiasgeihs** [comment]
same here

**Comment by samankittani** [comment]
There is a way around this, but it is ugly. If you define a newtype for Vec<String>:
`pub struct VecString(Vec<String>);`
Then you can impl From<JsValue> for VecString.
`impl From<VecString> for JsValue {
    fn from(value: VecString) -> Self {
        serde_wasm_bindgen::to_value(&value).unwrap()
    }
}
`
You will need serde_wasm_bindgen. 
I can't impl it for Vec<String> directly because of Rust's orphan rule. You'll need the serde_wasm_bindgen crate. I am trying to find a more elegant solution

**Comment by samankittani** [comment]
Here is a better solution #3630
This will likely be fixed in the next release. In the meantime, I am adding this to my cargo.toml file:
[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "88efe46" }
This will use the wasm-bindgen version that includes the commit that supports Vec<T> for async functions

**Comment by daxpedda** [comment]
Considering #3630 has already been merged, I'm gonna go ahead and close this.
Let me know of this turns out to still not be fixed.
