### ISSUE TITLE
Console warning: "using deprecated parameters for the initialization function; pass a single object instead"

### ISSUE THREAD

**Issue by TheMythologist** [rustwasm/wasm-bindgen#4122]
I am currently encountering this issue: https://github.com/swc-project/swc/issues/9443

Seems like the `default_module_path` is performed too late, only after the object destructuring check:
https://github.com/rustwasm/wasm-bindgen/blob/8e66719182441eb5da5f15dcee75e475dbea2db5/crates/cli-support/src/js/mod.rs#L898-L906

Is it possible to shift this default block to the top of the function (or at least before the object destructuring)?
Alternatively, if the intention was to ensure that the default would be provided in the event that `{}` was provided, could you add an `else if (typeof module_or_path !== 'undefined')` before emitting the warning in the console? Or would you recommend swc to change the [recommended way](https://swc.rs/docs/usage/wasm) to `await initSwc({})`;

**Comment by TieWay59** [comment]
I am currently building the browser extension template project at https://github.com/Mubelotix/wasm-extension-template. When I deploy this template extension to the latest Chrome browser, I get this warning. I think it's a similar situation.

![image](https://github.com/user-attachments/assets/9c276e4a-bc47-4bf6-b127-bed69f6c7693)

**Comment by alpancs** [comment]
@TheMythologist this problem exists in version `0.2.93` bot **not** in version `0.2.92`.

try this to confirm it in your work environment:
```toml
[dependencies]
wasm-bindgen = "=0.2.92" # not "0.2.92" or "0.2"
```

**Comment by TieWay59** [comment]
I won't be able to help with the testing of wasm-bindgen 0.2.92. The reason is that my project has dependencies on several other libraries, which in turn depend on wasm-bindgen version 0.2.93. Unfortunately, this dependency structure prevents me from testing version 0.2.92 without potentially causing conflicts or breaking changes in my current setup.

I understand the importance of testing different versions, and I wish I could be of more assistance. If there's anything else I can do to help or if you have any other requests, please let me know.

> @TheMythologist this problem exists in version `0.2.93` bot **not** in version `0.2.92`.
> 
> try this to confirm it in your work environment:
> 
> ```toml
> [dependencies]
> wasm-bindgen = "=0.2.92" # not "0.2.92" or "0.2"
> ```

Sorry, I'm not able to help with the testing of wasm-bindgen 0.2.92. The reason is that my project depends on several other libraries, which rely on wasm-bindgen version 0.2.93. Unfortunately, this dependency structure prevents me from testing version 0.2.92 without potentially causing conflicts or breaking changes in my current setup.

I wish I could be of more assistance. If there's anything else I can do to help or if you have any other requests, please let me know.

<details><summary>Details</summary>
<p>

```bash
❯ cargo tree 
demo02 v0.1.0 (/home/taiwei.wu/github/webextplaygrand/demo02)
├── chrono v0.4.38
│   ├── iana-time-zone v0.1.61
│   └── num-traits v0.2.19
│       [build-dependencies]
│       └── autocfg v1.3.0
├── console_error_panic_hook v0.1.7
│   ├── cfg-if v1.0.0
│   └── wasm-bindgen v0.2.93
│       ├── cfg-if v1.0.0
│       ├── once_cell v1.19.0
│       └── wasm-bindgen-macro v0.2.93 (proc-macro)
│           ├── quote v1.0.37
│           │   └── proc-macro2 v1.0.86
│           │       └── unicode-ident v1.0.13
│           └── wasm-bindgen-macro-support v0.2.93
│               ├── proc-macro2 v1.0.86 (*)
│               ├── quote v1.0.37 (*)
│               ├── syn v2.0.77
│               │   ├── proc-macro2 v1.0.86 (*)
│               │   ├── quote v1.0.37 (*)
│               │   └── unicode-ident v1.0.13
│               ├── wasm-bindgen-backend v0.2.93
│               │   ├── bumpalo v3.16.0
│               │   ├── log v0.4.22
│               │   ├── once_cell v1.19.0
│               │   ├── proc-macro2 v1.0.86 (*)
│               │   ├── quote v1.0.37 (*)
│               │   ├── syn v2.0.77 (*)
│               │   └── wasm-bindgen-shared v0.2.93
│               └── wasm-bindgen-shared v0.2.93
├── js-sys v0.3.70
│   └── wasm-bindgen v0.2.93 (*)
├── percent-encoding v2.3.1
├── wasm-bindgen v0.2.93 (*)
├── wasm-bindgen-futures v0.4.43
│   ├── cfg-if v1.0.0
│   ├── js-sys v0.3.70 (*)
│   └── wasm-bindgen v0.2.93 (*)
├── web-extensions v0.3.0
│   ├── gloo-utils v0.1.7
│   │   ├── js-sys v0.3.70 (*)
│   │   ├── serde v1.0.210
│   │   │   └── serde_derive v1.0.210 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.86 (*)
│   │   │       ├── quote v1.0.37 (*)
│   │   │       └── syn v2.0.77 (*)
│   │   ├── serde_json v1.0.128
│   │   │   ├── itoa v1.0.11
│   │   │   ├── memchr v2.7.4
│   │   │   ├── ryu v1.0.18
│   │   │   └── serde v1.0.210 (*)
│   │   ├── wasm-bindgen v0.2.93 (*)
│   │   └── web-sys v0.3.70
│   │       ├── js-sys v0.3.70 (*)
│   │       └── wasm-bindgen v0.2.93 (*)
│   ├── js-sys v0.3.70 (*)
│   ├── serde v1.0.210 (*)
│   ├── serde_derive v1.0.210 (proc-macro) (*)
│   ├── serde_json v1.0.128 (*)
│   ├── thiserror v1.0.64
│   │   └── thiserror-impl v1.0.64 (proc-macro)
│   │       ├── proc-macro2 v1.0.86 (*)
│   │       ├── quote v1.0.37 (*)
│   │       └── syn v2.0.77 (*)
│   ├── wasm-bindgen v0.2.93 (*)
│   ├── wasm-bindgen-futures v0.4.43 (*)
│   └── web-extensions-sys v0.4.1
│       ├── js-sys v0.3.70 (*)
│       ├── wasm-bindgen v0.2.93 (*)
│       └── wasm-bindgen-futures v0.4.43 (*)
├── web-extensions-sys v0.4.1 (*)
└── web-sys v0.3.70 (*)
```

</p>
</details>

**Comment by daxpedda** [comment]
> Or would you recommend swc to change the [recommended way](https://swc.rs/docs/usage/wasm) to `await initSwc({})`;

No changes are necessary. This is a bug in `wasm-bindgen` v0.2.93 and was fixed in https://github.com/rustwasm/wasm-bindgen/pull/4074.

**Comment by allsey87** [comment]
I am still getting this error in v0.2.95, when building with the `web` target. This the html that I am using to instantiate the module:
```html
<script type="module">
    import init from "./wasm-rayon-test.js";
    init()
</script>
```
This produces the error since the "first" argument to init is `null` for which `typeof` returns `'object'` instead of `'undefined'`.

**Comment by daxpedda** [comment]
That's strange, I'm unable to reproduce this.
AFAIK undefined parameters shouldn't be `null`, they should indeed be `undefined`.

Maybe there is something else involved here?
E.g. does Rayon call `init()` somewhere to instantiate modules in workers?

**Comment by allsey87** [comment]
You can use [this repository](https://github.com/allsey87/webapp-mandelbrot-rayon) to reproduce the problem. You can open it in GitHub codespaces and once it's built, run the build/serve script `run.py`

**Comment by daxpedda** [comment]
> You can use [this repository](https://github.com/allsey87/webapp-mandelbrot-rayon) to reproduce the problem. You can open it in GitHub codespaces and once it's built, run the build/serve script `run.py`

Just looking at `wasm-bindgen-rayon` I can see [its didn't update how it executes the `init()` function](https://github.com/RReverser/wasm-bindgen-rayon/blob/09ade9bc064402df85e4b8ac9791ea5866a898ba/src/workerHelpers.worker.js#L25), so I assume its just that.

If you still want me to try it out locally I'm happy to if you compile the whole thing for me so I just need to serve it without all the tooling around it.

**Comment by lmf-git** [comment]
You get that error in latest using it in any JS project, at least via -compat.

```
<script context="module">
  import * as RAPIER from '@dimforge/rapier3d-compat'
  await RAPIER.init()
</script>
```

**Comment by Mon-ius** [comment]
still get this error when with,

```toml
[dependencies]
wasm-bindgen = "0.2.100"
getrandom = { version = "0.3", features = ["wasm_js"] }
```
